### ISSUE TITLE
Another reproduction of Grasmann.jl

### ISSUE THREAD

**Issue by chakravala** [Jollywatt/GeometricAlgebra.jl#1]
Your effort would be better spent contributing to [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) since your design is based on my design and you're just ending up redoing what I've already done, only in a less sophisticated way. Your repository isn't bad at all, but it's just going to end up being a lesser copy of my work it seems.

**Comment by Jollywatt** [comment]
I appreciate the concern and am aware of Grassmann.jl — although I disagree with your sentiment.

To your claim that this is based off Grassmann; it really isn’t, other than being in part inspired by it.

More generally, I am aware that there are many other geometric algebra implementations for Julia:
- [ATell-SoundTheory/CliffordAlgebras.jl](https://github.com/ATell-SoundTheory/CliffordAlgebras.jl)
- [serenity4/GeometricAlgebra.jl](https://github.com/serenity4/GeometricAlgebra.jl)
- [digitaldomain/Multivectors.jl](https://github.com/digitaldomain/Multivectors.jl)
- [velexi-research/GeometricAlgebra.jl](https://github.com/velexi-research/GeometricAlgebra.jl)
- [MasonProtter/GeometricMatrixAlgebras.jl](https://github.com/MasonProtter/GeometricMatrixAlgebras.jl)
- in the future, [JuliaGeometricAlgebra/GeometricAlgebra.jl](https://github.com/JuliaGeometricAlgebra/GeometricAlgebra.jl)

My reasons for diverging from these implementations mostly involve different ideas about internal design. This is true also for Grassmann, but in addition I think our goals differ. While similar in functionality, I’m wanting a package that:
- for users, has a minimal, unimposing type system;
- for developers, is simple enough internally to be understood;
- for researchers, is unopinionated (that is, uses only widely-established terminology and symbols);
- implements ‘only’ geometric algebra, without a more abstract framework which may be burdensome to beginners. (Admittedly, your [whitepaper](https://crucialflow.com/grassmann-juliacon-2019.pdf) is impenetrable to me — and so is most of the source code.)

So yes; by your reckoning, I may end up with a ‘lesser’ version of Grassmann. At the same time, by my reckoning, the monolithic, idiosyncratic quality of Grassmann is an opportunity for something ‘better’. We are all making open source software here.

**Comment by chakravala** [comment]
Let me know how your opinion of terminology and symbols is unopinionated, I would be interested to see your opinions. I also don't see how your type system is minimal and unimposing.

**Comment by Jollywatt** [comment]
> Let me know how your opinion of terminology and symbols is unopinionated, I would be interested to see your opinions.

All I mean by this is that I want to use names such as _blade_, _multivector_, $\bullet$, $\wedge$, $\times$ which are widely used in Clifford/geometric algebra, specifically, and only those. Grassmann has many more exported symbols, many of which are unfamiliar to me:
```
Chain, ChainBundle, DiagonalForm, Dyadic, DyadicChain, DyadicProduct, I, Manifold, MultiGrade, MultiVector, Orthogrid, Proj, Projector, Signature, Simplex, SparseChain, SubManifold, TensorAlgebra, TensorGraded, TensorMixed, TensorNested, TensorTerm, UniformScaling
×, ǂ, Δ, Λ, δ, χ, ₊, ₋, ↑, ↓, ∂, ∇, ∗, ∥, ∧, ∨, ⊕, ⊖, ⊗, ⊘, ⊙, ⊛, ⊠, ⋅, ⋆, ⟂, ⨼, ⨽, 𝒫
```
However, notation is largely irrelevant — the point is that Grassmann appears to be much more than just an implementation of geometric algebra, which is another reason this repo won’t end up being a reproduction.
